repos:
  - repo: local
    hooks:
      - id: flutter-format
        name: Flutter format
        entry: flutter format --set-exit-if-changed
        language: system
        pass_filenames: false
      - id: flutter-analyze
        name: Flutter analyze
        entry: flutter analyze --no-fatal-infos
        language: system
        pass_filenames: false

