name: Commit Message Lint

on:
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./commitlint.config.mjs
          failOnWarnings: false

